using System;
using Demo1.Backend.ViewModels;

namespace Demo1.Backend.Domain
{
    public class Customer
    {
        public Customer(CreateCustomerViewModel viewModel)
        {
            this.Name = viewModel.Name;
        }

        public Customer()
        {
        }

        /// <summary>
        /// Generated by DB
        /// </summary>
        public long Id { get; set; }

        public string Name { get; set; }

        public string CreditCardNumber { get; set; }

        public bool IsPremiumMember { get; private set; }

        public DateTimeOffset InvitationMailSentAtUtc { get; set; }

        //public DateTimeOffset ConfirmedAtUtc { get; set; }

        public void UpgradeToPremium()
        {
            IsPremiumMember = true;
        }
    }
}